### ISSUE TITLE
Huge lags when downloading a lot of videos

### ISSUE THREAD

**Issue by khivus** [futo-org/grayjay-android#101]
I started downloading the playlist with 170 videos and inside downloading menu app started to lag a lot. It laggy only in downloading tab.

**Comment by koen-futo** [comment]
Just curious, does a restart of the app fix it? Might be a memory leak.

**Comment by khivus** [comment]
@koen-futo 
I apologize for not answering earlier on this issue.
I tried again, restarting the application does not help. I'm now on version 233 and this issue still there. Also I found that when one video finishes downloading the app freezes. 
While I was testing I got error:
[GrayJayAppError.txt](https://github.com/futo-org/grayjay-android/files/14168381/GrayJayAppError.txt)

**Comment by Kelvin-FUTO** [comment]
Looking over your log & your description, I suspect its simply that the downloads UI wasn't really built with 170 *active* downloads in mind. 
Since it was originally made with the idea of users manually downloading individual videos. So downloads would always finish before it becoming an issue. Playlists however allow you to download 100s of items in 1 click.

Looking at your log says your phone is not liking having that many items on screen. Unlike completed downloads, active downloads aren't paged, especially thumbnails can take a lot of memory. Finished downloads should not have this issue, as they are properly paged.

This of course this should be fixed, however I believe it should not impede the download if you do not open the Downloads tab while it is downloading correct?

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
