### ISSUE TITLE
Youtube Home page is showing trendings instead of my YouTube home page

### ISSUE THREAD

**Issue by mathix420** [futo-org/grayjay-android#1055]
This was working fine a couple days ago, and now I have only trending videos which I'm not at all interested in.

Grayjay home
![Screenshot_20240604-085802.png](https://github.com/futo-org/grayjay-android/assets/37625778/8d519a0d-3b31-47f8-80ef-dc69d7456413)

Youtube trending 
![Screenshot_20240604-085833.png](https://github.com/futo-org/grayjay-android/assets/37625778/3de59abc-50b2-44f0-967f-4220858ef8da)

"Normal" YouTube home page
![Screenshot_20240604-090039.png](https://github.com/futo-org/grayjay-android/assets/37625778/804f317f-ff8b-453b-a793-1ceaa1d338ce)

**Comment by JacobPlaysGames** [comment]
I might have a temporary workaround. If you "Logout without clear" under the YouTube source settings and sign in again you should see your regular YouTube recommendations on the home page. This issue seems linked to the same reason that subscription import won't work. At some point the app stop treating users like they are signed in.

**Comment by grayjay-support-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
