### ISSUE TITLE
Unable to Export Polycentric Identify

### ISSUE THREAD

**Issue by WeareTheDraiken** [futo-org/grayjay-android#1065]
I've been using Grayjay for like 2+ weeks now, so I tried to export my Polycentric Identify but every time I do so I'm unable too.

I am able to make a polycentric account externally on the web and log in, in grayjay , but I don't want to do that as I would end up losing all the comments I've made so far (which is a lot).

If the export polycentric Identify feature was know not to have worked from the the beginning, I wish it had bern pointed out when I installed to make the account externally on yhe web first.

Anyway I really would like this to be fixed please, so I can log into the same account on another phone.

**Comment by golgothan666** [comment]
pretty sure it used to work

i've done it before, if i remember correctly... but just tried it because i've noticed my comments haven't been posting for 3 weeks... only to have the key retrieval crash/freeze

guess i need to save the key in an offline file, if it ever gets fixed

**Comment by Auster-1** [comment]
What isn't working? Just tried exporting, and after maybe 30s~1 min of the app hanging with a message "Grayjay isn't responding", the share and copy options appeared, so if your issue is Grayjay hanging, maybe try to wait a while longer?

It does seem, however, like it's a very resource-intensive process, so, in the lack of more information, I can also presume your phone may be running out of processing capacity.

**Comment by Auster-1** [comment]
Testing even further, created a new profile on a laptop with BlissOS (desktop Android) installed. Export option worked immediately, and besides the share/copy option, it even shows a QR code now. A few minutes before, I reopened Grayjay on my phone and tried sharing the export, and Grayjay is sitting there like nothing happened, not even freezing or crashing.

**Comment by Zvonimir-FUTO** [comment]
This has been fixed in the upcoming version of Grayjay v265.
