### ISSUE TITLE
[HTTP Plugin API] JSON Decode error

### ISSUE THREAD

**Issue by VoxelPrismatic** [futo-org/grayjay-android#1071]
# Summary

I am trying to write a plugin for Floatplane, but am coming across this mysterious error with no traceback:
```
JsonSyntaxException:java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BOOLEAN at path $
```

# Steps to reproduce
1. Have a Floatplane account
2. Use the plugin at [VoxelPrismatic/grayjay-floatplane](https://github.com/voxelprismatic/grayjay-floatplane)
3. Log in
4. Call `getHome()` on local test (not android test)

# Additional information
It is unable to even return the response body to the client. Perhaps this is a unicode error? I have [attached](https://github.com/user-attachments/files/15831558/response.json) the output I get when calling `https://www.floatplane.com/api/v3/content/creator/list?ids%5B0%5D=61bc20c9a131fb692bf2a513&limit=20` for your reference.

# Version details
Android 14
Samsung Galaxy S22; OneUI 6.1
Grayjay 242 Release

**Comment by Bluscream** [comment]
@Kelvin-FUTO @koen-futo lets get this fixed!

**Comment by stefancruz** [comment]
Hi, I can try to help. In a few hours I can have a look into this.

**Comment by stefancruz** [comment]
Hi @VoxelPrismatic,
The issue you are having is because http.GET is missing the header param. It has expecting the header param but got the bool for useAuth.

Here https://github.com/VoxelPrismatic/grayjay-floatplane/blob/main/FloatplaneScript.js#L285

Instead of: 
`const home = http.GET(API.HOME.CREATOR_LIST + query, true);`
You should have something like:
`const home = http.GET(API.HOME.CREATOR_LIST + query, {}, true);`

I hope this helps.

**Comment by VoxelPrismatic** [comment]
Will this still use the `Cookie` as set by the authorization browser?

**Comment by stefancruz** [comment]
Yes, it will. The third bool parameter (useAuthClient) from the [HTTP](https://gitlab.futo.org/videostreaming/grayjay/-/blob/master/docs/packages/packageHttp.md?ref_type=heads#package-http) package ensures that.

Also, just so you know, if getHome needs to be always authenticated, you may want to return an empty ContentPager when not authenticated.

Something like this:

```
if (!bridge.isLoggedIn()) {
    const hasMore = false;
    return new ContentPager([], hasMore);
}
```

**Comment by bmlzootown** [comment]
Author of Hydravion here -- I happened upon this issue while looking into Grayjay, and I’m supportive of a plugin like this as an alternative to the AndroidTV app. Since early 2023, I've been working 6-day weeks (salaried retail), which has left me with limited time and energy to dedicate to the project. It’s been difficult just keeping up with everything going on at work, let alone anything outside of it, and for now, that’s unlikely to change. Given the current circumstances, it’s hard to say when I'll be able to focus on the project again, but I’m always open to community contributions or exploring alternatives like this project. Apologies for the inactivity.
