### ISSUE TITLE
Cancelling feed reload too soon results in a broken state

### ISSUE THREAD

**Issue by Matti-Koopa** [futo-org/grayjay-android#11]
Steps to reproduce:
* Swipe down on a feed list, like the "Home" feed
* As soon as the white circle with the spinning load indicator appears, immidiatly tap away to another tab (like "Subscriptions")
* Tap back to the "Home" tab

What I expected:
It's still loading, loading finished or loading was cancelled.

What I got instead:
The spinning load indicator is stll there, bt there is no actual loading beeing done. Also, swiping down to initiate a new reload doesn't work anymore. It's stuck in this state.

Extra info:
If you change tab too late and have one plugin already finished loading but the others not, a toast message with "Job cancelled" will appear and the Home feed will have loading placeholders for the other plugins stuck in a loading animation even though it isn't loading anything anymore.

Potential solution:
Re-trigger a reload event on switching tabs if the previous wasn't finished prior to switching tabs. Or, alternatively, continue loading feeds in the background even if it's not the active tab anymore.

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay.
Currently, it will just stop the job when switching tabs and you will have to re-trigger reload which solves the bug problem of the issue. 

You can still open feature request for continuing loading feeds in the background even if it's not the active tab anymore.
