### ISSUE TITLE
Automatic background playback like in NewPipe

### ISSUE THREAD

**Issue by DominikAgejev** [futo-org/grayjay-android#1197]
### Use Cases

I was listening to a video in the background on cellular and sometimes unlocking the phone to view the screen, however, judging by the fact that all my data is gone GrayJay keeps donwloading the video in the background, not audio only.

I didn't have this problem with NewPipe which plays audio only when in the background.

I propose an option of automatic switching to audio only when on cellular, wifi or both or just implement it as it works in NewPipe, that was perfect for me.

I would also like a play in background option right on the search screen like in NewPipe (hold on video to see option).

Thanks on advance.

**Comment by sigboe** [comment]
If you disable PIP I think it works more like how you expect. Only downloading audio when outside the app or locked phone. PIP is still accessible by the Overlay button so no functionality lost. 

My main issue with this is that there is a gap of like 1/3 of a second (if grayjay doesn't need to buffer) where it switches to the other playback method. It's longer if it needs to buffer some data. Hope this issue can be fixed by the clever developers soon

**Comment by DominikAgejev** [comment]
You're right, it already works, but only for YouTube. I was trying with Rumble and Odysee and background playback doesn't work at all.

Yes, the delay is a bit annoying and NewPipe has no delay when switching.
