### ISSUE TITLE
Youtube activity isn't syncing 

### ISSUE THREAD

**Issue by abster95** [futo-org/grayjay-android#1232]
### What happened?

Sending watched activity to YouTube stopped working. I checked the plugin and it's enabled there. I tried disabling than re-enabling.

I can't see my watched activity when I go to YouTube.com. The watched tracking is working in Grayjay app, but I'm getting recommended videos that I already watched on the homepage and I can't continue where I left off on YT.com

I'd be fine with auto hiding watched videos locally as well, but would like the full behavior back if possible. Paying user btw. 

Device: Zenphone 9
System: Android 14

### Grayjay Version

253

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

190

### When do you experience the issue?

- [X] While logged in
- [ ] While logged out
- [ ] N/A

**Comment by pauel3312** [comment]
Same issue here. See https://github.com/futo-org/grayjay-android/issues/826#issuecomment-2267424327 ( #826 ) for more info

**Comment by abster95** [comment]
Didn't find that open issue on gh yesterday whike checking. I see it's from Feb. Do we close this as a duplicate or leave this one to track the new behavior

**Comment by pauel3312** [comment]
I think we should leave it open. Behaviour seems different, and the other one seems to have went under the radar

**Comment by pauel3312** [comment]
as of latest YouTube plugin version (191), this seems to be fixed

**Comment by sigboe** [comment]
@pauel3312 I'm on YouTube plugin 191 and it is still not working for me. I tried to log out and in again but the problem persists. Did you do anything to fix the problem?

YouTube is becoming less and less useful to me as this problem persists over time, since I keep getting recommended videos I've watched already. Right now most the videos in my recommended lists is what I've watched already, need to scroll quite a bit to get something new.

Maybe it's good to be less addicted to YouTube

**Comment by pauel3312** [comment]
> Did you do anything to fix the problem?
I just updated the plugin and it worked. I am on grayjay version 253.

> Maybe it's good to be less addicted to YouTube
I completely agree.

**Comment by sigboe** [comment]
@pauel3312 seams to me that the ios user agent method to unblock videos is the one that prevents watched history to work.

I went back to try out Revanced again and it has the same issue. And it is a documented issue on revanced forum

**Comment by AvaHurstCode** [comment]
>  seams to me that the ios user agent method to unblock videos is the one that prevents watched history to work.

This follows what I've experienced too, currently my entire feed is full of watched videos as this issue has been around for me since this issue was opened. I have fully updated both grayjay and the youtube plugin however I get the "ios user agent" message at the bottom of my screen when I play a video, which tracks with what you mentioned. 

I believe this issue should be reopened so it can be properly addressed and others can provide more information if available.

**Comment by pauel3312** [comment]
I also have the iOS user agent message on my side, but it seems to work flawlessly.
