### ISSUE TITLE
Subscription feed is empty

### ISSUE THREAD

**Issue by wallefan** [futo-org/grayjay-android#1237]
### What happened?

GrapheneOS on Pixel 7a.  I have subscribed to several channels across YouTube, Oddysee, and Peertube, and although I can see my list of subscribed channels just fine under the Creators tab, and I can click on any of those channels and see an up to date list of videos, if I select the Subscriptions tab, it shows a loading throbber for a moment and then nothing appears, and I see an error popup telling me it failed to fetch some channels.

I'm unsure how to view the logs.  I enabled logging, restarted the app, reproduced the issue, and pressed the Submit Logs button, and it told me it did so via a toast message containing some form of UUID (which I took a screenshot of) but I don't know where it actually sent them.  Would be glad to help if there's any other information you need or other things I can try involving the developer mode.

### Grayjay Version

253

### What plugins are you seeing the problem on?

All

### Plugin Version

N/A

### When do you experience the issue?

- [ ] While logged in
- [X] While logged out
- [ ] N/A

**Comment by Quackdoc** [comment]
I'm getting a really similar issue, my subscriptions page is empty, I can sometimes make them show up by toggling posts off and on.

Also live content is now showing up as `videos` with a 0:00 duration

**Comment by vijay-prema** [comment]
I'm also suddenly seeing this issue since about a month ago. Everything was working fine for months until now.

I can still see all the videos if I click on one of the creators I subscribe to, the aggregated feed that shows at the start is just blank all of a sudden.

**Comment by vijay-prema** [comment]
OK I solved this issue.  It was due to user confusion.
There is a row of buttons on the feed like this:
![image](https://github.com/user-attachments/assets/cc7c23b3-9538-4b74-bdd1-0b21c453c1c4)
It is hard to notice but these are actually filter toggle switches and two of them are actually switched off

Simply switch them back on:
![image](https://github.com/user-attachments/assets/eff75acb-90a4-4838-9c46-4c6b0e6c4f78)

Then the videos will all show.

Personally I think this is a UX issue. I have been using this app for nearly a year and I never really noticed these toggles, and it is hard to tell when they are on/off.

**Comment by support-grayjay** [comment]
@wallefan Could you please confirm the solution @vijay-prema posted works for you or are you still facing the issue?

In my opinion toggles are noticeable but we might look into some highlight colors for activated pills once we get to focus on theming.

**Comment by Zvonimir-FUTO** [comment]
Closing issue due it becoming stale.
