### ISSUE TITLE
No results on rumble source. 

### ISSUE THREAD

**Issue by gebeleixis** [futo-org/grayjay-android#1251]
### What happened?

Searching for creators doesn't return any rumble result, just a black page. Search is active in plugin page, I tried  only rumble plugin. 

### Grayjay Version

253

### What plugins are you seeing the problem on?

Rumble

### Plugin Version

44

### When do you experience the issue?

- [X] While logged in
- [X] While logged out
- [ ] N/A

**Comment by WinstonSmith73** [comment]
I have this issue also on Pixel 6 Pro, CalyxOS Android (latest release), GrayJay v253, Rumble plugin v44, logged-in. I get no Rumble channel creators, only their YouTube & Odysee channels.

**Comment by skdecoteau** [comment]
Same here, on Pixel 7a with latest Android 14 update. I get errors when I click on subscribed Rumble channels, either "Failed to get channel" or "stream was reset". Same versions.

**Comment by codebymatter** [comment]
I noticed error messages woth the Rumble plugin after the latest YouTube plugin update last week. The problem had gone away after a few hours but I see the messages sometimes on 4G LTE data. Errors relate to the Rumble plugin not being able to fetch content data and sometimes buffers much more when my mobile connection is throttled due to high-traffic hours.

Nite this sometimes happens but other than that it's working.

**Comment by support-grayjay** [comment]
This seems to be fixed in latest version of Rumble plugin. Feel free to open a new issue if you are still encountering this.
