### ISSUE TITLE
com.futo.platformplayer.playstore - Not uninstalling PeerTube

### ISSUE THREAD

**Issue by UnidentifiedTag** [futo-org/grayjay-android#126]
The Play Store version of GrayJay "com.futo.platformplayer.playstore" isn't allowing the uninstall of PeerTube

to reproduce : download Grayjay "[here](https://play.google.com/store/apps/details?id=com.futo.platformplayer.playstore)"
open GrayJay and press sources, press the preinstalled PeerTube, press uninstall, press confirm, you get a notification to say PeerTube has been uninstalled however it remains. 
Video of issue : https://github.com/futo-org/grayjay-android/assets/54625394/f4d0e227-baa1-477a-a1d7-e361fe3ec1f9
the version of GrayJay directly from futo site does not suffer from this issue found "[here](https://grayjay.app/index.html#download_footer)"

**Comment by UnidentifiedTag** [comment]
> Desired behavior when uninstalling a plugin is it should not be reinstalled upon bootup. Perhaps additional UI is necessary to allow users to manually reinstall an embedded plugin.

The necessary UI to reinstall the PeerTube plugin is "[here](https://[plugins.grayjay.app](https://plugins.grayjay.app/)/)" so users could reinstall if needed, as PeerTube is listed as an installable plugin
I do agree however, that a link to the plugins page "with in the app/grayjay" would make it clear you can reinstall these plugins when uninstalled or even get new ones

**Comment by Kelvin-FUTO** [comment]
The reason we choose not to allow this is because Grayjay needs at least 1 plugin to function, and there is no UI to reinstall embedded plugins yet. Grayjay effectively checks on startup if embedded plugins are missing or outdated, and then reinstalls them.

Installing external plugins is not the same as reinstalling embedded plugins.
Embedded plugins are preferred over external ones as they auto-update on apk updates.
(This is also why our own apk from the website is better than the one from the Play store, less chance of various issues)

Uninstalling embedded plugins would purely be visual, as disabled plugins don't do anything in the first place.

**Comment by UnidentifiedTag** [comment]
Understood, I'm going to close this as it seems to be intended behaviour for now 👍🏻

**Comment by koen-futo** [comment]
Reopening because this should be implemented (eventually)

**Comment by b-risk** [comment]
> Uninstalling embedded plugins would purely be visual, as disabled plugins don't do anything in the first place.

Actually disabled plugins still give an update popup, this is especially annoying for plugins which are disabled so will not be used anyway but still force you to update them.

**Comment by Zvonimir-FUTO** [comment]
> > Uninstalling embedded plugins would purely be visual, as disabled plugins don't do anything in the first place.
> 
> Actually disabled plugins still give an update popup, this is especially annoying for plugins which are disabled so will not be used anyway but still force you to update them.

You can disable check for update inside plugin settings for ones you disable them while you wait for us to make this a default :)

Also the original issue has been fixed.
