### ISSUE TITLE
No Rumble Results

### ISSUE THREAD

**Issue by Vader1222** [futo-org/grayjay-android#1263]
### What happened?

Every search I've made in the last few days for a creator that I know has a Rumble account is not showing in the creator lookup function. I have the Rumble plugin enabled, fully updated with the latest version at the moment and it's my second right after YT for search and content results.

### Grayjay Version

253 release

### What plugins are you seeing the problem on?

Rumble

### Plugin Version

44

### When do you experience the issue?

- [ ] While logged in
- [ ] While logged out
- [ ] N/A

**Comment by skdecoteau** [comment]
I'm having a similar issue. Same versions.

**Comment by Mangoes** [comment]
It's working fine for me (just tested it now).

**Comment by codebymatter** [comment]
> It's working fine for me (just tested it now).

Same with me, cab login and everything. Wish some of these issues expressed included specifics besides the wrror dumps like "l'm on VPN and rhis was working fine before..." or "I'm on a proxy network.".

My phone is not a 4GB RAM capable phone (Its a SM-A037U) and I do encounter the occasional freezing and performance hiccuos and that isostly because of Multitasking apps. Having Edge opened and Grayjay running Background will cause it to be bumped from memory and close. And vice-versa. Not so much with Brave but again lack of sufficient memory. 60% of apps are webapps.

**Comment by support-grayjay** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
