### ISSUE TITLE
Ability to combine channels into a single "creator"

### ISSUE THREAD

**Issue by Sainan** [futo-org/grayjay-android#1294]
### Use Cases

Greyjay is advertised as being a platform to "follow creators, not channels," yet all that can be done is follow/subscribe to _channels_. A trivial example of this would be Jet Lag: The Game. They have an active presence on both Youtube and Nebula, both supported by Greyjay, and yet, if I were to actually follow both via Greyjay, I would see every video twice in my subscription feed.

### Proposal

I propose that you actually be able to follow creators, by specifying their channel(s), resuling in a better presence in the subscription feed, e.g. by pruning or collapsing multiples of the same video in the subscription feed.

**Comment by Kelvin-FUTO** [comment]
We already support this, but our current design is to be creator driven, meaning that a creator needs to verify their accounts so no false positives happen.
We've been thinking about doing this in an automatic fashion, or even user specified, we just haven't gotten to it.

We already support deduplicating videos from the same account.

**Comment by MKBontwikkeling** [comment]
I use the groups fuction for it now. That way I combine all the creators channels in one. That way I can also see from what platforms the video is coming from. Using for instance Rumble over Youtube to support alternatives. This isn't the most elegant solution because it clutters the groups-function, making it less usable.

Maybe crowd source the selection process. IF > 500 users combine 2 channels as one creator THEN combine 🤷🏾‍♂️

**Comment by support-grayjay** [comment]
This will be resolved through #244.
