### ISSUE TITLE
Completed vids still show up in start page

### ISSUE THREAD

**Issue by phobiusmobius** [futo-org/grayjay-android#1580]
### What happened?

I expect completed videos to not appear on the start page.
![Screenshot_20241209_074838_Grayjay](https://github.com/user-attachments/assets/785a9d84-8c03-48d9-904a-88f4b7376137)

### Grayjay Version

268

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

218

### When do you experience the issue?

- [X] While logged in
- [ ] While logged out
- [ ] N/A

**Comment by Zvonimir-FUTO** [comment]
It appears you did not enable "Provide Youtube Activity" in Youtube settings which is causing this issue. If it fits your threat model that would solve your issue.

The reason you get these results is because Home page pulls Youtube's recommended videos to you which you watched and Grayjay keeps track of them but Youtube doesn't. We are planning on adding filters similar to Subscription page which will enable you to filter watched content.
