### ISSUE TITLE
Refresh shows most of the same vids.

### ISSUE THREAD

**Issue by phobiusmobius** [futo-org/grayjay-android#1581]
### What happened?

when I refresh on the start page, nearly all the videos stay the same, or the number of videos decreases to 4-7 vids, which are still nearly all the same as before. Android Version btw.

### Grayjay Version

268

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

218

### When do you experience the issue?

- [X] While logged in
- [ ] While logged out
- [ ] N/A

**Comment by Zvonimir-FUTO** [comment]
Related to #1580.

**Comment by Zvonimir-FUTO** [comment]
It appears you did not enable "Provide Youtube Activity" in Youtube settings which is causing this issue. If it fits your threat model that would solve your issue.

The reason you get these results is because Home page pulls Youtube's recommended videos to you which you watched and Grayjay keeps track of them but Youtube doesn't. We are planning on adding filters similar to Subscription page which will enable you to filter watched content.
