### ISSUE TITLE
Login brings me to YouTube web

### ISSUE THREAD

**Issue by Pverte** [futo-org/grayjay-android#1608]
### What happened?

Hi ! 
I installed for the first time Grayjay today, and when I want to login to my YouTube accounts, similarly to the issue #152, each time I'm loggin in it brings me to the YouTube Web interface, and when I go back Grayjay thinks that the login failed, making that I'm not logged in on Grayjay BUT if I click on the "login" button I'm connected on my youtube account but on the YouTube web interface.

### Grayjay Version

276

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

219

### When do you experience the issue?

- [ ] While logged in
- [ ] While logged out
- [X] N/A

**Comment by Zvonimir-FUTO** [comment]
Apologies if I misunderstood something but it seems you are trying to log in to Youtube but failing because it's not intuitive similarly like in another user in this comment: https://github.com/futo-org/grayjay-android/issues/1423#issuecomment-2541768696

Here is my comment from that comment thread:
>Here you should select your channel just there where you censored it. This is youtube's login flow and we can't change that.

**Comment by Pverte** [comment]
HAHA thats a strange way, thank you !
