### ISSUE TITLE
[Feature Request] [YouTube plugin] SponsorBlock integration

### ISSUE THREAD

**Issue by syboxez** [futo-org/grayjay-android#17]
SponsorBlock is, for me personally, a must-have feature for the YouTube plugin.

If anyone is not aware, SponsorBlock is a project that allows for the automatic skipping of sponsor segments in YouTube videos, along with other optional segments, such as the intro and outro, and self-promotions.

Since SponsorBlock works via user-submitted reports, having the ability to submit to the SponsorBlock database from within Grayjay would also be a nice feature to have.

**Comment by AnekinRed** [comment]
I personally think that just having it be a sponsor block thing maybe isn't enough.
Cause these guys pay creators and help them make money of the platforms so blocking all of them would be screwing the creators over pretty unfairly by removing a source of revinue if you ask me.
However the problem with most sponsors is that they are either garbage products like raid shadow legends and almost every other mobile game sponsor and then there are the actual scams and the ones that are really harmfull to the user.
So I propose a system where we have a multi tiered sponsor block.
Which you can naturally toggle on and off individually.
The different tiered sponsors would exist to separate the garbage sponsors from the few good ones out there. So you can flag a sponsor as a garbage sponsor. And have them be flagged as garbage based on the amount of people who have flagged them as garbage.
And once they are flagged as garbage the sponsor gets sent to the garbage tier letting you tag future sponsor segments you see of them with it.
A system like this would allow people who wanna see good sponsors see them and block the garbage ones aswell.
The goal of the system is to make sure creators and people who wanna sell you a potentially useful or cool product don't get unfairly screwed over by people who wanna rid the platform of garbage by indiscriminatly blocking every sponsor whilst simultaneously giving those who want the option to just block everything that option.

**Comment by EmeraldSnorlax** [comment]
using sponsorblock does not directly impact creators though, afaik? sponsors are usually paid by view count, by conversions, or by a lump sum upfront. you skipping over a sponsor will not affect these metrics in the slightest.

**Comment by AnekinRed** [comment]
You've got several good points here although it is a direct revanue source which would suck for the creators if removed.
It will be removed if nobody ends up watching the segments anyway.
Cause why throw away money into something if it's not gonna work.

> part of what makes sponsorblock great is the amount of crowdsourced data. fragmenting this effort will make both sponsorblock and your implementation worse. not to mention the futile nature of trying to classify "garbage" sponsor in any meaningful way outside report bombing

Although this very much depends on the paramentars for the qualifications but it could be argued that scewing the system the other way would make it too easy to exploit and that there is no right value that it can be set as to be perfect.

The entire point of it was to maybe get a way for creators to not lose probably their most vital revenue stream in sponsors whilst simultainiously removing harmful and actively malicious products from as much of the public as possible.
I do not wanna see sponsors as much as the next guy and I would much rather have the current system than no system at all.

However by doing stuff like this we are screwing over people who just wanna let others know about a niche product which would not be found naturally or organically via internet searches. The point of advertising and sponsors is to get your product into a spotlight where potentially interested people could see them. Removing this will take away a large platform for new products or ideas to grow and spread. It will be stunting the growth of a lot of small startups and keep those who are already household names in the top ready to keep exploiting.

Am I asking for a lot here? yes yes I am.
Am I extremely Biased? yes and I very much am looking to start my own shit because I wanna create cool stuff and I want it to reach a large audience, and sponsors and advertising is the best way for me to do so.
However I do not wanna see shit like Raid Shadow Legends in my videos and I doubt any of you guys want it either.
But I also doubt you wanna remove a platform for competitors to the large abusive and exploititive corporations to make themselves known either.

GrayJay itself was popularised due to marketing and advertising.
Sure maybe you or the next guy don't particularly wanna have any advertising which is why I suggested the option to just nuke everything still be there.
And I realise the crowd I'm speaking too probably doesn't share the same values as me but we can agree that letting people have options and choose for themselves would be nice.

And as for what to classify as garbage sponsor that's pretty simple.
Literally anything and everything which is harmful to the customer.
Scams and spam.
And a lot of other things which could be classified as it.
I don't have all of the answers and I should not be the one to decide anything.

They could also be tagged as garbage based on a report and review system.
say one user sends in a report for a garbage sponsor another user could varify it and tag the brand of the sponsor as garbage.
resulting in every sponsor segment which has the branding in it be tagged as garbage.

there are a billion ways to implement this and I'm not really gonna be that bothered if people don't end up liking this kind of thing or just decide to not do it.
It's either way gonna end in sponsors getting blocked and that's all that really matters.

I'm open to brainstorm this more though to find ways to improve it cause I think it's fun even if pointless.

**Comment by brnl** [comment]
@AnekinRed That's a lot of words but no matter what you say, [SponsorBlock](https://sponsor.ajay.app/) is already a thing. And it's **amazing**! If it won't be added to this app, I just wont use the app. 

I think sponsor sections are even worse than ads because the creator you love, potentially LIES to you (about loving a product) just for some cash. I don't need to hear and see that. ;-)

And: How is running SponsorBlock different to blocking any other ads?

By the way, SponsorBlock doesn't only block sponsors, it let's users skip all kind of sections. Really great for smooth and efficient watching experience. Try it!

**Comment by syboxez** [comment]
I would suggwst a compromise then. Implement SponsorBlock normally, but disable it by default.

Most users of software are going to stick to default settings, bur the people who are annoyed by sponsors, or people who want to skip other non-content segments of videos can do so by manually going to the settings and enabling SponsorBlock.

As for me personally, I cannot tolerate YouTube without SponsorBlock, and not having it implemented will prevent me, along with many other people from using GrayJay at all.

**Comment by AnekinRed** [comment]
I'm not agaist sponsorblock in any sort of way as it is. It works brilliantly and I used it on revanced and I have the extenstion installed on my browser and I used it until I stopped using youtube on my desktop cause I can't live without adblock on.
I just wanted to raise a point and to consider things from multiple perspectives and weigh in my perspective here.

I said so I don't really care if my idea or a compromise happens or not so long as sponsors are getting blocked I'm happy and what we have works.
And I'm well aware of the effects of advertising and I'm in general quite educated in this.
However sponsors are fundamentally different from normal advertising in that the contract is formed directly with the creator on an individual basis unlike normal ads.
This allows one to build a quality controll of some kind in what goes and doesn't on a creator basis.

Creators have no control over which ads are shown but they do controll which sponsors are shown.
And by accepting a sponsor you are endorsing a product.
If they don't actually like the product and only did it for the money then you shouldn't have trusted the creator in the first place.

Overall I do not really care in what form sponsor block is integrated so long as it is integrated.
I just wanted to try and look at things from a different perspective and think of a solution.

I think that this has been something of an experience and I did learn a few things from this.
Mainly being that it's not actually that bad to have a lot of people dissagree with your opinion so long as you treat the other opinions with some level of respect despite dissagreeing in some cases.

Despite it all and thinking a bit more about the situation.
This was probably extremely pointless since a simple and good solution already exists and perfectionism isn't exactly necessary.
But oh well now I know.

Anyway I don't think I have much more to say on the subject.
To everyone who ended up reading through this I apologize for wasting your time and have a nice day.

**Comment by candroid-man** [comment]
I'm not going to read this entire conversation, but I read enough to contribute I feel. SponsorBlock should be added, and correct me if I'm wrong, but currently nobody can add it themselves and distribute it to the public due to the proprietary license (#18).

I understand that people generate revenue from sponsors, and I agree that it should be off by default, however it already exists and it is necessary in a YouTube app. Watching an LTT video without SponsorBlock is so bad I refuse to watch those videos without it, and a lot of people feel this way. Most of these sponsors are terrible ant-consumer companies anyways, and the majority of the creator's money comes from the initial sponsorship agreement if I'm not mistaken. I mean take NordVPN for example, we all know they don't value your privacy, but these creators have to rep them for their liveleyhood, which is totally understandable but users should have the ability to skip all that BS

**Comment by OkieNeck** [comment]
No SponsorBlock is a deal breaker for me. They already have a less capable ad blocker so the difference would be it's better. Adding the ability to skip in video ads would have ZERO ill effects on creators. Besides you should be donating directly to creators you want to support, not waisting your time watching garbage ads for utter tripe so you can add $0.0001 to their adsense payout! Seems like asking for someone to make a fork that's better to me.

**Comment by Bluscream** [comment]
I made some preperations for Sponsorblock: https://github.com/Bluscream/GrayJay/commit/05c7195efb2bf66d0f77a97df37e36b14022530a

But i think plugins need more access (OnPlayerProgresses) event or smth so sponsorblock can work

**Comment by Kelvin-FUTO** [comment]
Due to strong demand version 191 has Sponsorblock for Youtube.
(FUTO respects your decision to use SponsorBlock. But only if you're supporting creators in other ways.)

**Comment by HueponiK** [comment]
Thanks a lot to delivering!

But why should this be limited to youtube? Any reason (besides monetization question) to not make it global? Sponsorblock works well with alternative domains like Invidious.

**Comment by brnl** [comment]
@HueponiK I guess it's a per-plugin implementation. So if you want it on other plugins as well, there should be another request, I guess.

**Comment by Bluscream** [comment]
> Due to strong demand version 191 has Sponsorblock for Youtube. (FUTO respects your decision to use SponsorBlock. But only if you're supporting creators in other ways.)

Thank you very much <3

**Comment by Bluscream** [comment]
You know invIdious is youtube, right?

**Comment by HueponiK** [comment]
https://github.com/ajayyy/SponsorBlock/issues/515

Sponsorblock itself is YouTube - only at the moment

I thought that, given the idea at the heart of Grayjay (platform independent following of the creators), the player function like this could be platform independent.

However if sponsorblock itself is bolted down to YouTube, there's nothing really to discuss.
