### ISSUE TITLE
Can't import past the first 75 items

### ISSUE THREAD

**Issue by benninkcorien** [futo-org/grayjay-android#186]
When trying to import YouTube subscriptions or playlists, you can't import past the first 75 items. 

Suggested solution: a "Load More" button that fetches the next 75.

**Comment by JustusW** [comment]
The current workaround is to import everything using select all, already imported channels are not shown again.

**Comment by jpalcantara** [comment]
It would nice to import from the Google take out!

**Comment by benninkcorien** [comment]
I don't want to import all subscriptions (just a small selection - so at some point 75 "don't wants" show and nothing else - moving to grayjay is a nice opportunity to weed out the time-wasters).

Import from CSV would be perfect! Then I can edit it before I import.

**Comment by Kelvin-FUTO** [comment]
Grayjay supports various import mechanisms. Since 190 importing from a newline seperated text file is supported.
You can create a textfile, of which the first line is "Subscriptions" or "@/Subscription", followed by channel url on each new line.

In version 190 the import cap was increased to 100, and better UI is to follow, or a better import flow in general from direct sources.

**Comment by MFGood** [comment]
This is my number one issue with the app at the moment, I'm not sure about YouTube since I don't have over 100 subscriptions to test with but with the Twitch plugin it seems like the limit might be stopping all of my follows from being imported, there's a lot missing. I know the Twitch API has a limit of 100 on results for this endpoint, but it seems like it's just calling it a day after that without advancing to the next page of results. Hope it can be addressed in future updates, I've wanted something like this project for a long time.

**Comment by Kelvin-FUTO** [comment]
> This is my number one issue with the app at the moment, I'm not sure about YouTube since I don't have over 100 subscriptions to test with but with the Twitch plugin it seems like the limit might be stopping all of my follows from being imported, there's a lot missing. I know the Twitch API has a limit of 100 on results for this endpoint, but it seems like it's just calling it a day after that without advancing to the next page of results. Hope it can be addressed in future updates, I've wanted something like this project for a long time.

This might be a different issue. You can simply import multiple times to get more results if it is the limit we added.
We just prevent more than 100 channels being fetched at a time.

If Twitch has an additional limit, and is not providing all channels, then that is a separate bug and I recommend creating a separate issue.

**Comment by koen-futo** [comment]
Load more has been added.
