### ISSUE TITLE
[Feature Request] Sort playlists

### ISSUE THREAD

**Issue by benninkcorien** [futo-org/grayjay-android#188]
Feature Request to sort playlists by

- video date (old to new/new to old)
- video name (A-Z/Z to A)
- video duration (long to short/ short to long)
- date added? (I think this is the default sort order, in case you want to get that back).
- shuffle (already exists, kind of, except doesn't actually change the order of the playlist, just plays a random video).

**Comment by koen-futo** [comment]
We'll add various sorting options in the future, stay tuned.

**Comment by paperfairy** [comment]
> We'll add various sorting options in the future, stay tuned.

Thank you! Will this include "Watch Later" too?

**Comment by benninkcorien** [comment]
Any ETA on playlist and watch later sorting?

**Comment by dimyself** [comment]
At minimum... Sorting (and also maybe searching) is needed for: downloads, playlists, and watch later.

These categories are almost unusable without proper sorting and a way to find videos. 

Downloads are only usable to me because I will download a video in my sub feed and click on it to watch from my sub feed... Forget about finding a downloaded video through the downloads tab

Same for playlists and watch later! I don't even use watch later because all the videos seem to be in a random order with no way to find anything. 

Playlist videos are the same... in a random order with no way to find videos other than manually scrolling / looking / hoping to find what you're looking for.

**Comment by Zvonimir-FUTO** [comment]
Duplicate of #78
