### ISSUE TITLE
YouTube doesn't update all subscriptions

### ISSUE THREAD

**Issue by W4RR4NTYK1LL3R** [futo-org/grayjay-android#290]
I consistently get a message "[YouTube] only updating 20 most urgent channels (rqs). (4 cached)"
The exact number of updated and cached channels varies, but is usually 19/5 or 20/4. Consequently, there are some channels who's videos don't update, but I don't know which ones without looking at each one individually. 
I assumed I'd find an explanation for this, but I haven't found one, and I don't see it in the open issues. Is it a bug or some limitation? If it is a limitation, what is the explanation? 
![IMG_20231112_125139](https://github.com/futo-org/grayjay-android/assets/126488013/63bfd656-28f9-44dd-8d28-b959220f8218)

**Comment by thebe14** [comment]
I guess it's a(n attempt to avoid some) YT rate limitation, but then it could update in the background, stretching it out over a longer period to get around that limitation.

**Comment by Kelvin-FUTO** [comment]
Could you name a channel that isn't updating?
20 channels is waaaaay below the ratelimit, so it is not updating those channels for a good reason. For example because they haven't uploaded in more than 6 months and thus it only checks it daily or every few days (hence it switches between 19/20).

The messaging is a bit confusing, I'll try to clarify it, at the moment it gives that notification even when it purposely didn't update channels (not due to rate limit) which might be confusing.

**Comment by W4RR4NTYK1LL3R** [comment]
Okay, so I was just going through each creator that I'm subscribed to via YouTube and I found the same type of thing with the latest video from MicrobeTV, posted 22 hours ago, where it only shows up under that channel in the Creators tab. But then I compared that to the channel on the YouTube app, and YouTube doesn't show that video either. This one was a livestream, so maybe that has something to do with it, but I suspect this may be more of a YouTube issue, and not an issue with the Grayjay app. I'm sure it's hard to list videos that YouTube isn't even showing for whatever reason. 
I'm going to go ahead and mark this closed. Thanks for your explanation.
