### ISSUE TITLE
Gestures for brightness and audio too easy

### ISSUE THREAD

**Issue by AidanG1** [futo-org/grayjay-android#3]
When swiping down from the top of the screen to check notifications, it is very easy to accidentally trigger brightness and audio gestures.

**Comment by null-von-sushi** [comment]
Agree. 
Personally I dislike those gestures in general, but I know some people really like them. Please let us disable the gestures for brightness and audio in the settings according to personal preference.

**Comment by JustCryen** [comment]
I feel like recently the gesture zone has been moved (shrinked) which is actually better than it was.
The option to disable it would still be useful but at least they're not that easy to accidentally trigger now.

**Comment by CroatZ** [comment]
Agree, but I also feel like it doesn't happen much anymore. Still, I would like to shrink areas for those functions further in landscape mode because I have gestures on my phone, and when I swipe from the edge sometimes I change the brightness and also sometimes when I try to press play/pause on video I accidentally reduce brightness. 
Also I would really like at least a volume option when phone is in vertical (small player) mode. I often find myself trying to change the volume after exiting from full-screen mode just to find there is no such option in small player and then I have to use physical buttons on my phone. It is confusing to switch constantly the way I'm changing volume.

**Comment by JustCryen** [comment]
Well, changing the volume with physical buttons actually negates the need for in-player volume controls.
At least In my opinion that is.

Additionally both, the on screen volume and brightness controls can't change their absolute system values but instead changes based on the current system value as in-player 100%. So it's only possible to change the volume / brightness down, not up (over the current system setting)

Which to be fair is why I actually somewhat like the brightness control. Because I can't accidentally blind myself by setting the max brightness in the middle of the night.
But yeah, volume is useless as I can just use the buttons.

**Comment by koen-futo** [comment]
Next build will feature many improvements to allow users to customize gestures. It also implements support for using system brightness and sound. Please reopen if anybody continues to experience issues.
