### ISSUE TITLE
Android complains app is not responding when it actually is

### ISSUE THREAD

**Issue by Subnet-Masked** [futo-org/grayjay-android#321]
Never seen something like this before. Unsure if Android bug or GrayJay bug. Once in a while I will get the popup that the app is not responding, I will tap wait because the app is in fact responding, but it keeps coming back up until I tell it to quit the app and reopen it.

I have a Google Pixel 7a running Android 14 build UP1A.231105.003 and security patch November 1 2023.

![Screenshot_20231116-124315.png](https://github.com/futo-org/grayjay-android/assets/55600371/c00da651-3806-487b-bfc7-8932b5c45635)

![Screenshot_20231116-124338.png](https://github.com/futo-org/grayjay-android/assets/55600371/d1f804e7-5d93-40ef-91ed-f3d244553898)

**Comment by ponko2MSL** [comment]
I've run into the same problem a few times, running Android 13 build 62.2.A.0.533 release-keys and security patch July 2023 on a Sony Xperia 10 III.

It's unclear what causes it, because most of the time the app runs fine without any issue for me, but every once in a while this error message will pop up in the middle of watching a video.

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
