### ISSUE TITLE
Kick search and subscription list doesnt work

### ISSUE THREAD

**Issue by shazamaru** [futo-org/grayjay-android#326]
Searching doesnt do anything and subscription shows Twitch subscriptions instead of Kick and it gives error that couldnt import subs

**Comment by Kelvin-FUTO** [comment]
Twitch subscriptions sound entirely unrelated to Kick.
There was a bug where Kick subscriptions would not show if the channel was live. This is fixed in upcoming version 199.
Kick has no video search (on their website) so we cannot implement this.
Kick does have creator search, which does already work (Creators Tab => Search)

**Comment by shazamaru** [comment]
Kick creator page and subscriptions gives onlyTwitch creators and when typing in creator search i get: Attempted to access non-whitelisted url: https://search.kick.com/multi_search (19)[[24-25] Plugin Kick (Beta)]   "source.searchSuggestions(...) "

But after clicking close it does let me creator search and it finds the Kick user while on subscription it doesnt (but as you mentioned its fixed in upcoming update)

**Comment by Kelvin-FUTO** [comment]
The Kick plugin is incapable of even accessing the Twitch website, so thats impossible (unless Kick themselves are showing them)

That error was solved in last update. If you're using the Google Play version, you need to manually update the plugins.

**Comment by shazamaru** [comment]
Just updated

1. Subscription page doesnt show anything except Twitch people i follow (even though the Twitch plugin is not enabled)
2. Creators page shows Twitch people i follow + the people i followed on Kick through the Grayjay app, the people that ive been following before on Kick dont show up

![1700853596464](https://github.com/futo-org/grayjay-android/assets/151107709/71dbb435-c36f-4a0a-bbda-aea87acde28e)
![1700853596462](https://github.com/futo-org/grayjay-android/assets/151107709/1124a127-3815-42a8-b8c8-6ddb41bf7976)

Thank you for the work and help, if i can help in any way with testing etc. let me know

**Comment by Kelvin-FUTO** [comment]
Disabling a plugin will not unsubscribe those people. They will stay in the list. Currently I believe if you do not reload your subscription feed, it might show the content cache, which may still contain Twitch results as we do not filter those by disabled plugins I believe.

Can you try enabling "Videos" in your subscription filters. Might be that it filters out Kick livestreams because of that.
