### ISSUE TITLE
[Issue] comment that I've just liked has zero likes

### ISSUE THREAD

**Issue by HafizBeyy** [futo-org/grayjay-android#333]
![Screenshot_20231118-155012_Grayjay.png](https://github.com/futo-org/grayjay-android/assets/120592808/be20ab9a-2fe5-4fb7-84e5-68587595e0a2)

![Screenshot_20231118-155000_Grayjay.png](https://github.com/futo-org/grayjay-android/assets/120592808/86617f61-2f2d-40cb-bcf0-756fa7d43f5f)

Even it has -1 likes when i get my like back

**Comment by aabd2** [comment]
This issue is written really inappropriately. This would be good candidate to be asked to be re-written with Summary that explains the issue shortly, as well as description defining the problem in words. Writing WTF on Summary and just posting 2 pictures without written description is about as useful usage of issues section as is possible.

Please change the Summary to be more descriptive of the issue itself. Also please include written description of the issue under the pictures of what exactly is wrong. I assume the problem is that the person got -1 when you gave thumbs up, but I can't be sure of it unless you give description explaining it.

**Comment by HafizBeyy** [comment]
Got it

**Comment by usertoroot** [comment]
To understand the issue... you place a comment, it starts out as 0/0, you vote on like and then...?

**Comment by HafizBeyy** [comment]
This is all the story: I saw that comment.liked it.then wrote down a comment.when back to comment's itself, i realized it shows 0 likes even though its highlighted (shows ive already liked it).and then when i got my like back,there was -1 like.

**Comment by Zvonimir-FUTO** [comment]
This is a bit old issue but can you reproduce it @HafizBeyy?

**Comment by Zvonimir-FUTO** [comment]
Issue is still present and will be resolved through the newer issue #1360.
