### ISSUE TITLE
Downloading & pop up

### ISSUE THREAD

**Issue by Mjwhite1108** [futo-org/grayjay-android#356]
No download=  **sources** not found. Please work on button for **pop** out mini **window** 
**Thank you. Great work. Keep up the fight for Foss and R2R!**

**Comment by Kelvin-FUTO** [comment]
I assume these are 2 different issues (better create seperate issues then).

Grayjay already supports Picture in Picture ("pop out window"?).
There is also a button for this which is under "More" called "Overlay" which manually triggers Picture in Picture instead of automatic (configurable in settings under Background Behavior).

I'm not sure what you mean be No Downloads=sources not found.

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
