### ISSUE TITLE
[Feature Request] Importing data through files

### ISSUE THREAD

**Issue by snowleaf0503** [futo-org/grayjay-android#376]
I hope there's a function where you can import subscriptions, playlists, and watch history through csv and json files just like what a lot of YouTube frontends do. This can make people import data without logging in to their Google account, which benefits people who already switched to NewPipe, Invidious, or Piped for a long time.

**Comment by Kelvin-FUTO** [comment]
Subscriptions can already be imported through various means.

**NewPipe**
You can import NewPipe subscriptions directly by using their Export subscriptions to json, and then opening that file in Grayjay.

**Text**
You can also use line-seperated .txt file where the first line says "Subscriptions" and every next line is a channel url:
```
Subscriptions
https://some.platform.com/someChannelA
https://some.other.platform.com/someOtherChannel
...etc
```
Opening this txt file with Grayjay will allow you to import it.

**Playlists**
Playlists have a similar format for importing but they are a bit less trivial. (You can share a playlist to any chat and see this format).


We already have some UI in the work to make these options more manually available within the app instead of only automatic like this.

**Comment by LeggoMahEggo** [comment]
One of the main things holding me back from switching from NewPipe to Grayjay is the easy import of not only subscriptions, but both playlists and watch history. In the current version of the app, it only mentions subscriptions, which is not enough for my usage. Adding the ability to import all of these at once from NewPipe to Grayjay would be hugely beneficial imo.

**Comment by Kelvin-FUTO** [comment]
General update for this thread:
New easier to use dialog was added last update (Found in settings "Import" or if you have no subscriptions on that page).

@LeggoMahEggo Reason we didn't yet is cuz NewPipe doesn't provide those other things in an easy format, just a database file. So its significantly more work to get that to work. Hence it hasn't gotten priority.
We'll see what we can do soon. We're currently in the middle of some new features/improvements.

**Comment by LeggoMahEggo** [comment]
> @LeggoMahEggo Reason we didn't yet is cuz NewPipe doesn't provide those other things in an easy format, just a database file. So its significantly more work to get that to work. Hence it hasn't gotten priority. We'll see what we can do soon. We're currently in the middle of some new features/improvements.

Thanks for the reply, much appreciated! I'll keep an eye out :)

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
