### ISSUE TITLE
Installation error, requires newer sdk version?

### ISSUE THREAD

**Issue by 8mab** [futo-org/grayjay-android#424]
Hi! I'm trying to install the APK package from APKPure and I got this message

```
> adb install "C:\Users\mab\Downloads\Grayjay_201_Apkpure.apk"
* daemon not running; starting now at tcp:5037
* daemon started successfully
Performing Streamed Install
adb: failed to install C:\Users\mab\Downloads\Grayjay_201_Apkpure.apk: Failure [INSTALL_FAILED_OLDER_SDK: Failed parse during installPackageLI: /data/app/vmdl1384971912.tmp/base.apk (at Binary XML file line #7): Requires newer sdk version #28 (current version is #27)]
```
What should I do?

**Comment by koen-futo** [comment]
Android 9 is currently the minimum supported version. In the future we will see if we can support a lower SDK version but for now we cannot.

**Comment by Martina-Neumayer** [comment]
That's totally lame that something below v9 is not supported. Way to many people are still using those systems and on lots of devices that will never be able to get some newer system upgrades. For example LG phone users, which are sitting ducks because of the manufacturer who stopped making any new devices. My husband had such phone and he can't your app. That's sad, because the device alone is working very fine even due to its age.
Btw.. why exactly you're can not support the v8 android version? It is technically speaking not so much far different from the 9 version. And nothing is there that I am aware of, what can impact somehow negative your application. It is only a matter of changing minimum version number. It doesn't need some extra specific to v8 recompolatins. Perhaps I will do such mod for myself and test it on my hubby phone just for my own curiosity? 🤔 Wil se.
