### ISSUE TITLE
FCast not working Tivo 4k

### ISSUE THREAD

**Issue by koen-futo** [futo-org/grayjay-android#441]
@Doubs115 mentioned there are FCast issues using FCast with his Tivo 4k

**Comment by koen-futo** [comment]
In issue #430

**Comment by Doubs115** [comment]
Oh, thanks for starting this.

So, from what I remmember from yesterday is I tried and succesfully installed Fcast onto Tivo 4k. Then went to grayjay > cast > entered in the info. From here it would just Uh, infinitely load.

I am acutely aware that it's probably the Tivo being screwed up and not F-Cast on its own. However, in the past, I was able to use IP casting on other things. So maybe FCast should have an option similar to that.
 
Other info: 
Normal casting also shows up for this device and also doesn't work and Infinitely loads. The Tivo 4k says it has built in chrome cast.

Right this moment I have to worry about finals because I am in college but I remmeber I will include more info later.

**Comment by koen-futo** [comment]
@Doubs115 With regards to the FCast issues, I'd be curious to see what the issue is. Is your Tivo 4K on the same network as your phone? Do you have a VPN? if so, did you try disabling it when you are trying to cast? You mentioned ChromeCast but it wasn't clear to me if it ever worked.

With regards to casting content from other sources... we could eventually make a plugin which scans local files for media and expose them as a Grayjay channel you can subscribe to. Maybe you can make a separate issue for that?

**Comment by Doubs115** [comment]
@koen-futo So for the chromecast no it doesn't seam to work normally either. Sometimes when I have tried to connect in the past it will go to the home screen on the Tivo without the remote. Other then that no dice.

VPN and network issues was my first thought aswell so I have also tried various things like, changing the Wi-Fi network to be the same one as there are two channels in my case. Disabling VPN, restarting both phone and Tivo. 

In the past I have been able to kinda get them to communicate with bluetooth. Additionally, if someone is on Peacock sometimes I can control that through my phone. I don't really know how that happens but it does. Maybe something to do with my google account being logged in I don't know.

Lastly, I am pretty sure I tried looking it up once about the different casting options and protocols. Correct me if I'm wrong but I thought I discoverd that there are more then one chromecast's aparently there is also google cast and another one I can't remember. I have a pixel 3a and am in the proccess of switching to a 7a with calyxOS. 

Hope any of this info is helpfull. At some point I will see if I can get the info from the Tivo aswell but not this week.

**Comment by Doubs115** [comment]
So sorry to waste the time, I just tried everything again and it works. I have no idea why. I don't know what changed. 
There have been both updates to fcast and grayjay so maybe something fixed it.
And I even tested it on a seprate phone and it works there too. I hate everything. 

I don't get it, a month ago I spent 3 days with it trying to get it to work and it only takes me 3mins and now it works. Now it even works normally without grayjay and I think without fcast. So that's nice to know it took a year off my life free of charge. At this rate I can only hope to reach 30.

Let's just hope my therapist has a good support system because they are going to need it.
