### ISSUE TITLE
[Feature Request] Auto-generated closed captions are difficult to read quickly

### ISSUE THREAD

**Issue by strapped-puppy** [futo-org/grayjay-android#450]
My request is for a fix to the way the auto-generated subtitles appear so they match the YouTube app's display of auto-generated subtitles. Currently, they do not and they are difficult to follow along.

**Comment by mingyee2** [comment]
@strapped-puppy I’ve noticed that when the subtitles are actually supplied in the video and not autogenerated, they do appear how you describe you would like them. This suggests this is a consequence of how the autogeneration works. Do you have the same difficulty with autogenerated subtitles directly in YouTube?

**Comment by mingyee2** [comment]
@strapped-puppy  You are correct about the subtitles appearing in a swapped order, shifting down rather than up, as is the norm. I too was bothered about that. But I wanted to clarify because the issue you submitted (and it still says it this way) is that the lines should appear together, which is not true even for YouTube. You might consider modifying the issue to be a fix to which way the subtitles are appended, unless you actually mean that you want the lines appearing together. If it is the latter, I might submit a separate issue about the wrong order, since that is easier for them to fix and might get rectified quickly.

**Comment by Zvonimir-FUTO** [comment]
It appears some comments are missing from this thread which makes is a bit confusing. Could you please open a new issue clarifying everything in detail?
