### ISSUE TITLE
Cannot manage Polycentric identity 

### ISSUE THREAD

**Issue by MrGrenadeMcBoom** [futo-org/grayjay-android#467]
When I attempt to manage my polycentric identity via the top Link in settings menu I am given a notification that polycentric is disabled. Scrolling to the bottom of the settings menu the toggle for polycentric is enabled. When I attempt to like a video or comment I am told that polycentric is disabled despite the toggle still being enabled.

**Comment by MrGrenadeMcBoom** [comment]
I am also now getting, "failed to initiative polycentric" when opening app

**Comment by koen-futo** [comment]
Hmm this means that your Polycentric database somehow is corrupted. Can you give me more information about the error you are getting? Does the dialog specify any details?

Additionally, has it ever worked for you or are you a new user?

**Comment by MrGrenadeMcBoom** [comment]
I am also getting "plugin failed: YouTube cannot read properties of user" I sometimes get a similar notification for rumble. 
Polycentric did work for me before I updated the app yesterday. 

Sent from Yahoo Mail on Android 
 
  On Sun, Dec 10, 2023 at 6:05, ***@***.***> wrote:   


Hmm this means that your Polycentric database somehow is corrupted. Can you give me more information about the error you are getting? Does the dialog specify any details?

Additionally, has it ever worked for you or are you a new user?

**Comment by YoshiOhDosd** [comment]
I am also currently having this same issue. I reinstalled 2ish weeks ago because of a issue where grayjay seemingly ram leaked and basically slowed down my phone until it crashed (a reinstall fixed it) but ever since I have had the issue of 
"Failed to initialise Polycentric ID"
"Null"
Whenever I log onto the app and I am unable to access Polycentric comments on any videos
Before my reinstall it worked perfectly fine with no issues whatsoever but whenever I attempt to manage my Polycentric ID within the settings I get told "Polycentric is disabled"
However the toggle at the bottom of settings is on and turning it off and on again doesn't change anything.

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
