### ISSUE TITLE
Notifications only half working

### ISSUE THREAD

**Issue by Doubs115** [futo-org/grayjay-android#488]
I Recently moved from a Pixel 3a running stock Vanilla android to CalyxOS on a pixel 7a.

Shortly before I uninstalled it from my pixel 3a notifications did work. However, from moving to my Pixel 7a, notifications have not worked a single time.
I bet it's probably because of Calyx OS, but regardless, GreyJay doesn't use Google for notifications so it should work. 

I have tried clearing cache among other things and nothing has worked.

**Comment by JustCryen** [comment]
Nah, it's not your OS.
I'm using an official OS on my asus ROG (pretty close if not actually stock android 11) and notifications also don't work at all.

**Comment by LogicReinc** [comment]
There could be a variety of reasons. I personally use notifications for a few channels and they do work (be it an hour late because I configured it to check once an hour).
There are 3-4 things required for notifications to work:
 - You need to enable notifications for a channel ofc, this you probably already found. Depending on the number of subscriptions, changes might take a while to be detected. If you have around a 100-200 subscriptions, this should be a non-issue. Soon we'll have subscription groups that allow more fine-grained update behavior.
 - You need to allow the app in android to give notifications, We do not manually request this yet, you need to enable it. I'll see if I can make sure this is manually requested in the next build. Go to the android app settings, and enable notification channels there. On newer Android versions it is likely disabled by default.
 - You need to enable Background updating in settings. In recent builds it warns you every time you try to enable notifications for a channel if you have it disabled. With this setting you configure how often it should check.
 
 I do not think Calyx OS is the culprit, as far as I know, Calyx is implemented correctly when it comes to background behavior, or at least I've read nothing that says otherwise.
 
 @JustCryen Especially official non-Google OS have issues with background updating sadly as brands try to improve battery life, including some major brands like Samsung  (Including ASUS in some situations https://dontkillmyapp.com/asus). Most popular apps do not use background updating but rely on Google push notifications. We do not, as we do not have servers for this data or know your subscriptions at all.

**Comment by Kelvin-FUTO** [comment]
There could be a variety of reasons. I personally use notifications for a few channels and they do work. (Configured hourly updates, and generally I get the notifications within an hour when my phone allows)

There are 3-4 things required for notifications to work:
 - You need to enable notifications for a channel ofc, this you probably already found. Depending on the number of subscriptions, changes might take a while to be detected. If you have around a 100-200 subscriptions, this should be a non-issue. In the near future we have subscriptions groups for more fine-grained control over update behavior.
 - You need to allow the app in android to give notifications, We do not manually request this yet, you need to enable it. I'll see if I can make sure this is manually requested in the next build. Go to the android app settings, and enable notification channels there.
 - You need to enable Background updating in settings. In recent builds it warns you every time you try to enable notifications for a channel if you have it disabled.
 
 I do not think Calyx OS is the culprit, as far as I know, Calyx is implemented correctly when it comes to background behavior, or atleast I've not read anything that states otherwise.
 
 @JustCryen Especially official non-Google OS have issues with background updating sadly as brands try to improve battery life, including some major brands like Samsung  (and ASUS in some situations https://dontkillmyapp.com/asus). Most popular apps do not use background updating but rely on Google push notifications. We do not, as we do not have servers for this data or know your subscriptions at all.

**Comment by JustCryen** [comment]
Thank you @Kelvin-FUTO for your answer!
I'm aware of two possible settings that might influence app notifications, which correlate to your first two points, Unfortunately I'm not aware of the last thing you mentioned (background updating) it's either not implemented in my system yet or I just can't find it (keep in mind, I'm on Android11).

Currently I have my battery and notifications set like this:
![Screenshot_20231213-153231143 (1).jpg](https://github.com/futo-org/grayjay-android/assets/41633661/ce79635f-3bde-4b68-8f86-a4f5e9b93485)

![Screenshot_20231213-153422656 (1).jpg](https://github.com/futo-org/grayjay-android/assets/41633661/5ce5f282-1960-4450-8791-f5e577db432b)

**Comment by Kelvin-FUTO** [comment]
@JustCryen Background updating is a setting inside Grayjay. Its underneath Subscriptions (you can also just search for it).
You have to set it to an interval like 1 hour, this means Grayjay update (and cache) your subscriptions every hour, and give notifications when it finds something new. You should also see a notification appear occasionally whenever Grayjay is updating your subscriptions with progress bar etc. 
The accuracy of this interval is solely controlled by your OS, hence my previous mention about some OS not behaving.

Until recently we did not warn the user that you had to enable it. Now whenever you do try to configure notifications for a creator we warn them in a toast.

**Comment by Kelvin-FUTO** [comment]
If you fail to get it to work, there is a small test you can do to rapidly verify if it works or not.
In the Grayjay dev settings there exists a button that manually triggers the background updating service.
Though some of the buttons in these settings can cause your app to crash, brick, or introduce security vulnerabilities. So be careful.
You can enable dev settings by tapping Grayjay version in settings 5 times, a new button appears at the bottom that opens these dev settings.
Under "V8 Script Testing" (incorrect header) there is a "Test Background Worker".
Clicking that will manually trigger the background service and it will try to update your subscriptions.

Note that the background updating is not allowed while Grayjay is open under normal circumstances.

**Comment by JustCryen** [comment]
Thanks, so GrayJay did in fact show me a notification, now I only have to check if it will do this on its own. ;P

**Comment by JustCryen** [comment]
And it didn't work since the manual check.
This suggests that Grayjay is either always seen as "open" so it's not refreshing by its own or is completely dead and won't initiate the check because the process is down.

**Comment by Kelvin-FUTO** [comment]
@JustCryen 
If the process is down it should allow background updating to do its job.
Only if its open in background it will not update, as it assumes you're doing other stuff.

One thing you can try is:
 - Ensure your notifs work (you said you tested it and works)
 - Set background updating to 15 minutes.
 - Restart the app once, to ensure it has the new update rate scheduled
 - Kill the app (Swipe it away)
 - See if in the next 15-60 minutes you see anything popup from Grayjay.
 
 As mentioned before, that 15-60 minute window is heavily affected by your phone OS manufacturer.
 On my phone it generally does it whenever I activate the phone screen or equivalent (batches work).
 
 I can see if I can allow it to update if its explicitly in background and not being used, requires some more checks..
 But there is no guarantee that it fixes it for you with this change, hence my previous questions.

**Comment by JustCryen** [comment]
Ohh, "background updating" was set to never… whoops.
I'm not sure if I did this by mistake or if this is / was at one point a default but I certainly missed it when trying to fix the issue.
I guess it's safe to assume that it will work now and further confirmation won't be needed xP

Thank you for your assistance! And sorry for bothering you.

**Comment by mingyee2** [comment]
@Kelvin-FUTO Can this be closed?

**Comment by Doubs115** [comment]
Been a second since I saw this, notifications randomly started working a little bit. I have a lot of subscriptions and I still don't see a lot of them. The notification does apear but a decent amount of time it doesn't give me a popup. Lastly, when I click on a notification it does't automatically go away in system notifications.

I did decrease time to update subscriptions to an hour or less like mentioned above. It didn't seam to do anything untill a week or 2 later.

So I can close this now but I would rather update the title and leave it. Still has issues but overall better then before.

**Comment by Kelvin-FUTO** [comment]
In the upcoming build, we prompt the user for enabling notifications and/or background updating at every turn if you're trying to enable a subscription notification. I hope this solves some confusion.

**Comment by Doubs115** [comment]
Small update: 
I sometimes get a notification that the notification job stops. 
Notifications seem to only work after a reboot or are random. 
I have probabbly around 300 subscriptions and that might be part of the problem.

Not only does the job fail because too many but I often lose what's importent and what's not. I think it would be better if subscriptions where tied to the groups that they are put in. Then have the subscriptions be added to one notification relating to that group. Maybe just the title's listed out and creator attatched.

This may help both problems.
