### ISSUE TITLE
Improve filtering for "Upload Date" in the video search result

### ISSUE THREAD

**Issue by xephos1one** [futo-org/grayjay-android#532]
Would be great to filter videos in the search result by upload date.
Currently it's only possible to filter by source.

E.g. YouTube has the following options: any date, last hour, last 24h, last 7 days, last ~30 days, last ~365 days
(they name them differently like "this week" instead of last 7 days but that's just wrong by YouTube as this filter doesn't only start on monday)

**Comment by Kelvin-FUTO** [comment]
This is already supported, but you need to disable the other sources for these filters to show up.

The search filters show only the filters that all platforms have in common.
(Eg. Having Youtube + Rumble enabled for search will show you filtering by upload date because both Youtube and Rumble support this.)

A tutorial will soon be easily available within the app that explains this.

**Comment by koen-futo** [comment]
https://rumble.com/v3tapny-how-to-search-on-grayjay.html it already is up!

**Comment by xephos1one** [comment]
Good to know, but that only explains why it doesn't work as intended.
When I have Youtube and Twitch for example it still should be possible to filter the upload date.
Every video has its upload date - even Twitch VODs - that is shown in Grayjay, so it should be possible to filter them somehow.

**Comment by mnbvasd** [comment]
I would like this too. I understand that not all platforms will support this, however it can be done locally, in a similar way to blocking creators from the home tab.

**Comment by koen-futo** [comment]
Perhaps in this case the issue is that some platforms do not support all filters yet.

**Comment by Zvonimir-FUTO** [comment]
This is working for plugins that support Upload Date. Please open separate feature request for each plugin that doesn't support this.
