### ISSUE TITLE
Move location of *add to queue* button and maybe video length

### ISSUE THREAD

**Issue by Doubs115** [futo-org/grayjay-android#538]
I am wondering if the little button next to the options could be moved to the right side. 
![IMG_20231220_222119](https://github.com/futo-org/grayjay-android/assets/77902749/5d434cf1-5498-4d4a-885c-b5328f58291d)

Right now it's here------------^ but could it be moved here ^
(hope that lines up or it won't make sense sorry)
In other words, far far right.

The reason I find this being and issue Is I often find myself trying to add a video to the queue only for it to play the selected video instead. 

The solution of moving it to the right is a simple and elegant solution in that the space isan't used for anything else, so the hitbox can be increased without interfearing with anything. Assuming all else equal this should solve this issue.

Other considerations/notes:
Note sure if grajay has the option but increasing the scale technically is a fix for this. The issue I have for this is with increased scale you lose information density.
In this case I have not had much issue with miss touching other buttons so the cost of less info doesn't make sense IMO.

However I fully admit the is technically a prefrence, I just happen to have meaty nubs and good eyesight. Bad combination for smartphones *shrug*.

Another related tweak would be moving the length of the video from the preview to above my hypothetical "add queue" button. It could be on the same line as the "1 day ago" text with a gap and to the right.

I have had rare instances it that the nontranslucent nature of the length indicator has obstructed "importent" info or details.

**Comment by Kelvin-FUTO** [comment]
In the upcoming build (>= 127) we changed up the UI slightly for thumbnail views. So that the buttons are ever so slightly larger, and the queue button is wider.
We also moved the queue button to the right instead of left, this should makes it easier to press too.

We didn't move it all the way to the right as we tried it and it didn't look very good.
That space is also actually used for nested/redirect content types, which you are likely not seeing widely yet if you only use Youtube, in which that space is used to show an icon of the parent source.

Those buttons require a general redesign at some point anyway, but this might improve it slightly at least.

**Comment by Doubs115** [comment]
New update works great! Understandable if it didn't look right but as it stands now it's perfect anyway.

**Comment by max-ishere** [comment]
How about swipe actions? You could place the configuration in the +options (long press thing). Tbh the queue system is my favorite feature of the app. Much better than YouTube's autoplay for my usecases.

**Comment by Doubs115** [comment]
lol didn't even think about that. Though if they did do that it would need to be tuned right. I have gotten frusterated  from other apps in the past (including youtube) where if I had the slightest angle to up or down it will register as left or right. Or vice versa.

And I have had the oppisite problem where swiping did nothing. Still though I like the thought.
