### ISSUE TITLE
Storage space not cleared if download cancelled midway

### ISSUE THREAD

**Issue by uigoku** [futo-org/grayjay-android#558]
The storage bar shows updated space taken up and it doesn't clear out the downloaded video's storage space.

**Comment by mingyee2** [comment]
I am fairly certain this is a UI bug, thankfully, since at least when I tried this, the next video I downloaded _decreased_ the amount of used space in my phone (probably because it forced an update of used space). Still worth fixing, ofc, since it could break other logic in the app (and is at least inconvenient).

**Comment by Kelvin-FUTO** [comment]
Its partially an UI bug, it indeed will go down after re-showing the view.
That being said, I've seen cases where audio track doesn't get properly left behind (because it does successfully finish).

In version 22 it properly deletes both, and also cleans up any remaining files at startup as well.
