### ISSUE TITLE
Suggestions not related

### ISSUE THREAD

**Issue by Berganzio** [futo-org/grayjay-android#583]
The suggestions aren't related to my interests at all. My home is full of trashy videos and I can't have a nice experience.

**Comment by Doubs115** [comment]
Although the app is privecy focused if you are trying to get recomendations you need to login with youtube.
This is because the algorithum youtube uses is not built into grayjay (as far as I can tell).

You also need to have history turned on, or atleast so I have heard. I havn't turned mine off so I might be wrong.

**Comment by Berganzio** [comment]
Since two weeks ago i was able to see Every recommendation without history
Turned on and with the YouTube account logged in.
Now is just horrible experience to use

Andrea

**Comment by Zvonimir-FUTO** [comment]
Closing issue as stale.
