### ISSUE TITLE
[Suggestion] Have a different solution rather than the mini text bubble thing below.

### ISSUE THREAD

**Issue by ORIOLESFan02** [futo-org/grayjay-android#593]
![Screenshot_20231230-155551](https://github.com/futo-org/grayjay-android/assets/48143202/35996eca-28c6-4892-b971-60e69ecc30dc)

It doesn't show the whole thing and tapping on it does nothing. I'm curious to see what it says, but I have no idea how to do so.

**Comment by ORIOLESFan02** [comment]
Also while we're add it, what does that error above mean anyways? It only happens when I go into my subscription feed.

**Comment by Kelvin-FUTO** [comment]
In the new version 222 we made a custom UI for these exceptions, which should make them now fully readable. (This would give us more info on what the underlying issue is).
If you encounter this issue again with subscriptions, please create a new issue with the exception so we can solve it.
(Especially knowing the channel would help us, because it is failing to fetch a specific Youtube channel)
