### ISSUE TITLE
Playlist import from backup failed: any type not implemented 

### ISSUE THREAD

**Issue by unmellow** [futo-org/grayjay-android#600]
I am trying to import a backup made from the playstore version into the websites version of the app.

Most of my playlists imported correctly but 3 of them failed.
![Screenshot_20231231-181943](https://github.com/futo-org/grayjay-android/assets/30985587/a60275e5-006b-49cb-bfb8-74c561e9816a)

I am rather confused and not sure what to try or ask.

**Comment by unmellow** [comment]
I deleted all the playlist that imported fine and made a new backup with only the problematic playlist.

**Comment by Kelvin-FUTO** [comment]
The reason those 2 videos fail is because they don't exist anymore, and got taken down.
The error is indeed incorrect. Because of the wrong error being thrown, it didn't gracefully ignore the video.
(and import the playlist anyway, as it assumed the video was available, but just temporarily broken)
 
 This is solved in Youtube plugin v163.

**Comment by unmellow** [comment]
Tysm I can confirm that the import was successful this time and the issue
can be closed
