### ISSUE TITLE
Add download sorting

### ISSUE THREAD

**Issue by koen-futo** [futo-org/grayjay-android#624]

**Comment by dimyself** [comment]
At minimum... Sorting (and also maybe searching) is needed for: downloads, playlists, and watch later.

These categories are almost unusable without proper sorting and a way to find videos. 

Downloads are only usable to me because I will download a video in my sub feed and click on it to watch from my sub feed... Forget about finding a downloaded video through the downloads tab

Same for playlists and watch later! I don't even use watch later because all the videos seem to be in a random order with no way to find anything. 

Playlist videos are the same... in a random order with no way to find videos other than manually scrolling / looking / hoping to find what you're looking for.

**Comment by Zvonimir-FUTO** [comment]
Duplicate of #78
