### ISSUE TITLE
Login to YouTube isn't working

### ISSUE THREAD

**Issue by Tsunami014** [futo-org/grayjay-android#697]
When I press login, it launches a web browser and prompts me to log in which I do but then nothing happens, it just takes me to YouTube. I can even go to my Google account settings from that page! There is a pop-up that says you have to select your profile to work but I don't know how and I can't see anything! Please help!

**Comment by Kelvin-FUTO** [comment]
After login, you should be seeing a page with a bunch of profiles (or just one). (channel switcher page).
You have to select one, and after that the login window should automatically close.

This is required otherwise it would randomly pick one for people, causing some of them to not have their data.

**Comment by Tsunami014** [comment]
Thanks for the clarification! I was using a YouTube account that was under an organisation that didn't allow some YouTube actions, including having a YouTube channel, so when I selected it it gave me an error. Signing in with a hint email account worked! Thanks!
