### ISSUE TITLE
Patreon says update available while not installed

### ISSUE THREAD

**Issue by alexandrughe** [futo-org/grayjay-android#699]
I never installed patreon, yet this morning it reported update available
Installed patreon via update button, notification went away.
Uninstalled patreon, update notification showsnup again
I understand uninstall isn't uninstall, but disabled sources shouldn't prompt for update
![Screenshot_2024-01-17-08-20-53-62_ca2ad563b57b5497046450f16b7718e2](https://github.com/futo-org/grayjay-android/assets/78537117/1c5ab0d9-c17a-4605-8f01-410c0796a77f)
![Screenshot_2024-01-17-08-17-06-74_ca2ad563b57b5497046450f16b7718e2](https://github.com/futo-org/grayjay-android/assets/78537117/12c9d98a-db5b-4757-90bd-2ff263c8982d)
![Screenshot_2024-01-17-08-16-59-72_ca2ad563b57b5497046450f16b7718e2](https://github.com/futo-org/grayjay-android/assets/78537117/05ac4a9b-7c59-464d-aa15-af972d6799ed)
![Screenshot_2024-01-17-08-15-59-21_ca2ad563b57b5497046450f16b7718e2](https://github.com/futo-org/grayjay-android/assets/78537117/657adaa9-0621-4d3d-95e7-703ce77b24f2)

**Comment by Kelvin-FUTO** [comment]
In the upcoming release (279+, today) there is a toggle inside each individual plugin that allows you to disable the update check.
Disabling it for all plugins by default would cause issues for people that might have disabled a source till it works.
But this should allow you to just disable it for all sources you do not care about.
The setting is easy to find, and is the first toggle you will see on the plugin detail page under the info.

Uninstalling embedded plugins are automatically reinstalled by design. In upcoming release the uninstall button is disabled entirely to avoid further confusion.
