### ISSUE TITLE
[Feature request] Mark videos as watched

### ISSUE THREAD

**Issue by tymwitko** [futo-org/grayjay-android#700]
Inside the "Video Options" section, there could be an option to mark video as "watched" without actually watching the video.

**Comment by grappas** [comment]
bump

**Comment by brightandshinyobject** [comment]
I would also like this feature.

**Comment by golgothan666** [comment]
maybe they've added it since being requested, as i only just noticed it the other day...

but, there is a "Watched" toggle near the top right, at least if you're using the Subscription tab... not sure about home, as i don't use it

![Screenshot_20240608_040304_Grayjay](https://github.com/futo-org/grayjay-android/assets/120536651/03a29110-118c-43e2-8bdd-9cd8eea35200)

**Comment by Nydragon** [comment]
dito

**Comment by Majed6** [comment]
This would be very useful. Much better than opening a video, skipping to the end and waiting for it to be marked as watched.

**Comment by remilvus** [comment]
Bump.

It could be done by swiping the video to the side - this way it wouldn't unnecessarily clutter the interface.

**Comment by brightandshinyobject** [comment]
Bump, this feature would be great.

**Comment by Majed6** [comment]
They added it a few updates ago.

**Comment by brightandshinyobject** [comment]
> They added it a few updates ago.

They did! It'sisted under "add to history". Thanks for pointing it out.

**Comment by Nydragon** [comment]
Thats great!

**Comment by tymwitko** [comment]
Can confirm it works, I'm gonna close the issue as completed
