### ISSUE TITLE
App does not respect system brightness settings.

### ISSUE THREAD

**Issue by Dragonjinx** [futo-org/grayjay-android#702]
The grayjay app uses the brightness level set from the player outside fullscreen. 

Expected behaviour:
After disabling both the brightness slider and system brightness options from settings, the app uses the brightness level that is set from the android dropdown menu.

Actual behaviour:
App continues to use brightness level set in the video player as its default brightness, irrespective of weather the feature is enabled or disabled from the settings.

**Comment by jjbarrows** [comment]
In portrait brightness is low
In landscape brightness is adjustable in app but doesn't stay when returned to portrait

**Comment by teaalltr** [comment]
I can confirm the issue

**Comment by JustCryen** [comment]
Since the newest 230 update dropped, The first thing I did is I disabled both, **System brightness** and **Restore system brightness** in the settings because it's currently broken and brightness goes only to a 100% when in portrait.

Unfortunately it's still broken even when these settings are disabled.
When using GrayJay in portrait mode, the system brightness, even if set by system to like 10%, shoots up to a 100% and can't be adjusted in the system dropdown menu.
What I mean by it is, when I try to adjust the system brightness, it does lower for a second but it instatntly goes up again.

Adjusting it in landscape works alright but only until I switch back to portrait, then it goes back to a 100%…
This behavior continues until I quit GrayJay OR enter GrayJays settings. Only then the true system brightness will be applied.

**Comment by Cixme** [comment]
For me:
- The app is set to a constant random brightness value that is unresponsive to the system's value
- Whenever I enter the player, it sets the same value of the app, I can change it using the player's UI, but not the system's
- After I exit the player, the brightness goes back to the aforementioned default value

**Comment by Kelvin-FUTO** [comment]
We'll try to look into this tomorrow.

**Comment by Kelvin-FUTO** [comment]
In upcoming version 233 we've modified some of the system brightness implementation, and have also disabled it by default.

Apparently some phones have a separate window brightness and a system brightness (causing a bunch of inconsistent results).
This causes a bunch of confusion all over the place. We've modified it to actually be using/modifying the global system brightness now, with the downside that it needs permission for this (it will ask for it).

If additional issues show up after v233, feel free to re-open this issue.
