### ISSUE TITLE
Crash when changing  audio devices

### ISSUE THREAD

**Issue by lolguy91** [futo-org/grayjay-android#705]
Stupid thing where I have to plug in my headphones before I open grayjay or else it crashes

headphone: SBKP 4 A1
device: modded codename "spezn"(I know the codename better than the marketing name from all the modding research )
mods: it is rooted and runs a slightly outdated version of linrageOS

**Comment by koen-futo** [comment]
Could you post a screenshot of the crash? Or are you not getting the crash activity?

**Comment by lolguy91** [comment]
![Screenshot_20240119-162629_Grayjay](https://github.com/futo-org/grayjay-android/assets/95227041/60281817-cc36-4a65-bb29-78e67a2b3127)
@koen-futo I just get this

**Comment by koen-futo** [comment]
What happens if you click wait? does the app function normally?

**Comment by lolguy91** [comment]
no, its frozen completely

**Comment by koen-futo** [comment]
Hmmm whenever you unplug your headphones at the moment it just calls an exoplayer pause. Made possible fix by moving this call to the main thread. It is likely related to your OS though, do other apps have the same issue?

**Comment by koen-futo** [comment]
In that case, lets hope the theoretical fix worked. Releasing a build tonight. Keep us posted.

**Comment by smerkley** [comment]
Replying here instead of making my own issue since it seems related -- whenever I change audio devices (Bluetooth devices in my case) the video player stops as if I had closed the video. Grayjay doesn't crash, and additionally it will only happen when I open the app. If I switch devices while it's in the background it will still play, but the moment I open the app the video stops. If I switch back to the original device before I open the app I can successfully open the app without the video stopping.

**Comment by lolguy91** [comment]
@smerkley make a new issue, my issue was just LineageOS, nothing to do with GJ
