### ISSUE TITLE
YouTube opening all links despite enabling grayjay

### ISSUE THREAD

**Issue by Wolrund** [futo-org/grayjay-android#716]
As of today, YouTube is suddenly opening all video links over grayjay. Even if I disable YouTube app it is opening the YouTube browser instead.

All links disabled for YouTube and all links set default for grayjay on my phone. Am I missing something that I need to change?

![Screenshot_20240118-180659](https://github.com/futo-org/grayjay-android/assets/59117874/9d072b26-576c-421d-b917-b560550c0fee)
![Screenshot_20240118-180715](https://github.com/futo-org/grayjay-android/assets/59117874/f25bddda-cc52-4cd9-a16b-59e605f21c98)

**Comment by Aynthem** [comment]
Came here to find an answer. Then I thought about checking the actual phone settings because they supersede the app settings. That worked for me. In your phone settings, search for default programs. Then open that link, navigate down to YouTube, and remove its permission to open links. Also, while you're there, make sure that GrayJay does have that permission. Then just make sure you have the appropriate links selected in GrayJay as you already have.

**Comment by Kelvin-FUTO** [comment]
As Aynthem said, there is fairly little we can do about this. If 2 apps support the same link, and it is not configured as "ask every time", it will often default to Youtube.
You're gonna have to turn it off the handling for Youtube (or set it to "Ask every time").
