### ISSUE TITLE
Why is link handling not supported on the play store version?

### ISSUE THREAD

**Issue by thecatontheceiling** [futo-org/grayjay-android#905]
I don't understand why this is unavailable there. I don't want to get the version of grayjay from the website as it offers me no way of knowing if there are updates available for the app or not.

**Comment by Kelvin-FUTO** [comment]
The app store version of Grayjay has no embedded plugins, and has no knowledge of any platform effectively.
Because how Android works, links need to be defined in the Android manifest, which is not something we can change after compilation effectively.

The non-Playstore version of Grayjay has in-build updating, meaning you wouldn't rely on the App store for updates in the first place (You get a prompt when you open Grayjay if there is a new version).

**Comment by xephos1one** [comment]
> links need to be defined in the Android manifest, which is not something we can change after compilation effectively.

> The best thing we could do for the Playstore version would be to handle _any_ url, but this might annoy some users.

Can't all possible links (like youtube.com, youtu.be or twitch.tv) be included in the Manifest regardless of the plugins installed?
As you can't verify those links they then have to be activated by the user in the app settings anyway - or am I wrong?

Like Organic Maps for example: They have one verified Link (omaps.app) but I'm also possible to click on "Add Link" and then have the option to choose which of 2 supported links (www.openstreetmap.org and ge0.me) to add to open in the app.

As it's possible with Organic Maps to use URLs they don't own it shouldn't be an issue here aswell, right?
