### ISSUE TITLE
[Feature Request] Video Zoom/Pinch to Zoom

### ISSUE THREAD

**Issue by gudenau** [futo-org/grayjay-android#98]
Modern smartphones have some super janky aspect ratios which forces letterboxing on most videos. I like to watch 16:9 content zoomed in to get rid of the letterboxing and try to prevent premature OLED usage where the video contents is.

A nice gesture for this would be to pinch to zoom and have it snap to the two zoom levels.

**Comment by alcatraz-zz** [comment]
I wish to request an additional feature to the one mentioned above and it's ability of panning the zoomed in frame. Be it with two or three fingers or whatever so normal users don't lose the sense of it snapping to the middle.

Why you ask? Often on these funky aspect ratio phones I find myself watching a longer video where the zoomed in frame is constantly cropping off important information on one side only. So I'm needlessly  watching a side that has no important content just to miss content on the other side. Like for example Louis Rossmann repair videos where there could be a face in the corner or a multimeter or power supply feed in the corner. These are long videos and trying to watch them zoomed out leaves massive black bars, difficulty of seeing, and risk of burning in the oled.

Thanks for reading!

**Comment by alcatraz-zz** [comment]
Here's an illustration for the less common usage case:
- A 16:10 tablet zooming up a 16:9 frame. 
(For phones it's in the other direction, much needed feature.)
![262190260-c50bba6a-ea74-4195-8bce-52307d47a706](https://github.com/futo-org/grayjay-android/assets/250045/bd35f4a1-ce1b-4370-abfd-ca7eca00bbdb)

**Comment by JustCryen** [comment]
A general zoom in option that gets triggered after user tries to zoom in more than the previous two snap points (after fill horizontal / fill vertical) would be greatly appreciated. This option would ideally not be restricted to showing only the center of the screen and allow to place the zoomed in area wherever on the video.

Sometimes it's really hard to read a small font on some videos, briefly showed documentation and so on.
Like a video or a tutorial when something is being showed on the PC, basically everything related to a UI sized to match a big display rather than a phone screen.

It would be necessary to add a snap point to a default video size as well, so it's easy to go back to default by "pinching" the video.

**Comment by RichardBronosky** [comment]
> Sometimes it's really hard to read a small font on some videos, briefly showed documentation and so on.

YES! Most of the videos I watch are about programming. I really miss the pinch-zoom feature is YouTube because I cannot read code recorded at 1080p or higher.

**Comment by koen-futo** [comment]
Implemented next build.
